Algoritmo "CONVERSOR TEMPERATURA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/10/2022
Var
   f, c: Real


Inicio
      Escreva("Qual a temperatura em Fº? ")
      Leia(f)
      c <- (f - 32) / 1.8
      Escreva("A temperatura em Celsius é de ", c:4:1, " graus")


Fimalgoritmo