Algoritmo "CONVERSOU MOEDA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/10/2022
Var
   reais, dolar: Real
Inicio
      Escreva("Quantos reais você tem? ")
      Leia(reais)
      dolar <- (reais / 5)
      Escreva("Você tem US$", dolar)


Fimalgoritmo